[tool.poetry]
name = "mimic3_ihm"
version = "0.1.0"
description = ""
authors = ["Atreya Shankar <shankar.atreya@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.1"
pandas = "^1.0.1"
tensorflow = "1.15.4"
keras = "2.1.2"
scikit-learn = "^0.22.1"
ipython = "^7.12.0"
PyYAML = "5.4"
Pygments = "2.15.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
